# Generated by Django 6.0.5 on 2026-05-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Ожидание"), ("paid", "Оплачено"), ("failed", "Ошибка")],
                default="pending",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID цены в Stripe"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID продукта в Stripe"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"),
        ),
    ]
